# Default settings for build stages
language: java
jdk: openjdk8

script: ./gradlew build compileJava_minJosm compileJava_latestJosm --stacktrace
dist: trusty
deploy:
  provider: releases
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file:
    - "build/dist/pt_assistant.jar"
  skip_cleanup: true
  on:
    condition: -n $GITHUB_TOKEN
    tags: true
    jdk: openjdk8
